### ISSUE TITLE
Build scripts

### ISSUE THREAD

**Issue by davidmpurdy** [B-Interactive/cloudflare-stream-wordpress#1]
I'm working on some updates and fixes to the official plugin (first up: getting the block fixed and updated), and saw you had a fork that looks more actively maintained. I love what you've done (API tokens!) and I'm all for contributing to an existing fork rather than starting yet another, but I don't see build scripts there, however. Do you have a build step for blocks in place (I know that hasn't been the focus of this fork)? If not, are you actively managing this fork and open to PRs for things like that?

**Comment by B-Interactive** [comment]
Hi David.  My hope had been to submit pull requests to the official plugin collaboratively, but I quickly ran into the roadblock of the Block build step.  I reached out to a contact at Cloudflare in **April 2022**, requesting the missing build scripts.  The contact appreciatively responded shortly after, saying they'd discuss it with the engineering team, and that's the last I've heard, to date.  I'll reach out again.

My projects couldn't wait though, so this repository represents a bolder approach at implementing features, largely based on my own needs.  When it's convenient, it steps away from the existing structural paradigms.  

I'd begun work on pull-requests to the official repository incorporating new features.  They weren't completed (or submitted) due to the missing build scripts, making it impossible to test and really get anywhere.  If you've solved the build issue, I'd like to re-visit that potential.  I welcome pull requests, suggestions and input of course.  Ideally, I'd also welcome Cloudflare's active oversight of their own repository, so the otherwise abandoned official plugin may see updates again.

**Comment by davidmpurdy** [comment]
Thank you for the background information. My overall impression is that the WordPress plugin is not a current priority for Cloudflare. My idea was that if we could fix it up and start improving it, maybe they'd be interested in making it more community maintained, or at least working with us to get it in the WordPress plugin repository. I would love it if Cloudflare was up for some ongoing role in a WordPress plugin, but given that they haven't addressed your simple version/author update PR from April, that seems unlikely.

I'm right with you on projects that can't wait. It looks like you're doing active work on this, so if it's alright with you I'll start opening some issues and sending PRs.

I'll split of architecture talk into a separate issue.

**Comment by davidmpurdy** [comment]
I'd like to add the `dist` directory to `.gitignore` as part of a build PR, since it will sometimes have a development build and generally means built files being in a lot of commits unnecessarily. How would you feel about adding a ZIP file to releases for the pre-built download option (and adding npm install/build instructions to the readme, of course)?

**Comment by B-Interactive** [comment]
Thank you David for the PR and the suggestions.
