### ISSUE TITLE
Shotcode sizing issues

### ISSUE THREAD

**Issue by noname-ever** [B-Interactive/cloudflare-stream-wordpress#28]
Hello.

I am trying to use your plugin. It works great where initial integration and setup is concerned. However, I am running into issues regarding "shortcode" usage for video rendering.
The issue is that the video player size is unreasonable. I attach the screenshot. 
<img width="1080" alt="Screenshot 2023-08-09 at 21 16 35" src="https://github.com/B-Interactive/cloudflare-stream-wordpress/assets/60624891/2c1ac4f4-507d-4094-b2f9-239a5c49f67f">

Regular player looks good:
![image](https://github.com/B-Interactive/cloudflare-stream-wordpress/assets/60624891/7e520e62-d7e5-4f21-8880-28451abf30f8)

Maybe you could take a look?

**Comment by B-Interactive** [comment]
Hi @noname-ever, I'll investigate now.

**Comment by B-Interactive** [comment]
This looks like it might be theme related, and can be replicated using the more recent standard WordPress themes.  Seeing as the issue is with the standard themes though, I would like to resolve it.

What theme are you using @noname-ever, so I can further test with that too?

These exhibit the issue:
- [Twenty Nineteen](https://wordpress.org/themes/twentynineteen/)
- [Twenty Twenty](https://wordpress.org/themes/twentytwenty/)
- [Twenty Twenty-One](https://wordpress.org/themes/twentytwentyone/)
- [Twenty Twenty-Two](https://wordpress.org/themes/twentytwentytwo/)
- [Twenty Twenty-Three](https://wordpress.org/themes/twentytwentythree/)

So far, these are themes that have _not_ had the issue:
- [Twenty Sixteen](https://wordpress.org/themes/twentysixteen/)
- [Twenty Seventeen](https://wordpress.org/themes/twentyseventeen/)
- [Genesis Framework](https://www.studiopress.com/themes/genesis/) + [Sample Theme](https://github.com/studiopress/genesis-sample)
- [Astra](https://wordpress.org/themes/astra/)
- [OceanWP](https://wordpress.org/themes/oceanwp/)
- [Neve](https://wordpress.org/themes/neve/)
- [GeneratePress](https://wordpress.org/themes/generatepress/)

**Comment by B-Interactive** [comment]
Ok, here's the rundown.

The Cloudflare player in this plugin is configured to the standard [responsive recommendation](https://developers.cloudflare.com/stream/viewing-videos/using-the-stream-player#responsive).

```html
<!-- padding-top calculation is height / width (assuming 16:9 aspect ratio) -->
<div class="cloudflare-stream" style="position: relative; padding-top: 56.25%">
  <iframe
    src="https://customer-<CODE>.cloudflarestream.com/<VIDEO_UID>/iframe"
    style="border: none; position: absolute; top: 0; height: 100%; width: 100%"
    allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture;"
    allowfullscreen="true"
  ></iframe>
</div>
```

Where this appears to fail, is in themes which do not define a `max-width` in any element that would be parent of the wrapping `div` in the above example.   In testing, once a `max-width` is defined in a parent element, it scales to the correct size (eliminating the black bars).

Some options I've found so far:

1. Define `max-width` in a parent element. How this then impacts the rest of your theme, would depend on the theme.  I expect that max-width would also need to respond to the defined break points.
```css
.some-parent-div {
   max-width: 650px;
}
```
2. Set `max-width` in the players div to 100%.  Depending on theme, the video may scale to fit the width of the page, which I expect will _not_ be desired at higher resolutions, but will probably be ok for smaller screens (phones).
```css
.cloudflare-stream {
   max-width: 100%;
}
```
3. Override the responsive player, with [fixed dimensions](https://developers.cloudflare.com/stream/viewing-videos/using-the-stream-player#fixed-dimensions).  Obviously, this will not be as responsive, and again attention would need to be paid to break points only this time, adjustments are specific to the player size.
```css
.cloudflare-stream {
   position: inherit;
   padding-top: inherit;
}
.cloudflare-stream>iframe {
   position: inherit;
   height: 366px;
   width: 650px;
}
```

I'm open to any ideas and suggestions, but it looks to be difficult to fix this on the plugin side, because the solutions are largely un**responsive**, requiring very theme specific fixes.

**Comment by B-Interactive** [comment]
In the [Twenty Twenty-Two](https://wordpress.org/themes/twentytwentytwo/) and [Twenty Twenty-Three](https://wordpress.org/themes/twentytwentythree/) themes, something like this might work:
```css
.entry-content {
    max-width: var(--wp--style--global--content-size);
    margin-left: auto;
    margin-right: auto;
}
```

In the [Twenty Twenty-One](https://wordpress.org/themes/twentytwentyone/) theme:
```css
.entry-content {
    max-width: var(--responsive--aligndefault-width);
    margin-left: auto;
    margin-right: auto;
```

**Comment by noname-ever** [comment]
Hi there!

The theme we are using is "Flatsome". I have read all of your messages and came to conclusion that the issue lies within a theme. I am grateful that you have provided many possible ways in how to try to fix it. I will try some of them in the evening and will share my results.

**Comment by B-Interactive** [comment]
I've had a look at a few [Flatsome demo themes](https://flatsome3.uxthemes.com/demos/), and there are a number of classes that make use of `max-width`.  You might try ensuring, if possible, that your Cloudflare Stream shortcode sits within such an element.

The below CSS declaration seems to be pretty consistent in the Flatsome themes I had a look at, so it'd hopefully be a case of ensuring your player sits within an element that makes use of at least one of these classes.

```css
.container, .container-width, .full-width .ubermenu-nav, .row {
    max-width: 1080px;
}
```

**Comment by B-Interactive** [comment]
I'm glad it was able to be resolved! :smiley:
